sudo: required
language: generic

services:
  - docker

before_script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

jobs:
  include:
    - stage: Build
      script:
       - user_ubuntu/build.sh
